import { register } from '@reacticulum/types';
import { Align } from './Align';
import { Bold } from './Bold';
import { Checkbox } from './Checkbox';
import { Color } from './Color';
import { Divider } from './Divider';
import { H1 } from './H1';
import { H2 } from './H2';
import { H3 } from './H3';
import { Input } from './Input';
import { Italic } from './Italic';
import { Link } from './Link';
import { Paragraph } from './Paragraph';
import { Radio } from './Radio';
import { Underline } from './Underline';

register(Align, 'align');
register(Bold, 'bold');
register(Color, 'color');
register(Divider, 'divider');
register(H1, 'h1');
register(H2, 'h2');
register(H3, 'h3');
register(Input, 'input');
register(Italic, 'italic');
register(Link, 'link');
register(Paragraph, 'paragraph');
register(Radio, 'radio');
register(Underline, 'underline');
register(Checkbox, 'checkbox');

export { Align } from './Align';
export { Bold } from './Bold';
export { Checkbox } from './Checkbox';
export { Color } from './Color';
export { Divider } from './Divider';
export { H1 } from './H1';
export { H2 } from './H2';
export { H3 } from './H3';
export { Input } from './Input';
export { Italic } from './Italic';
export { Link } from './Link';
export { Paragraph } from './Paragraph';
export { Radio } from './Radio';
export { Underline } from './Underline';
